/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.billing.sw;

import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;

/**
 *
 * @author ASUS_PC
 */
public final class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setdate();
    }
    
    public void setdate(){
    ActionListener actiondate=new ActionListener() {

        
        @Override
        public void actionPerformed(ActionEvent e) {
            java.util.Date mydate=new Date();
            lblDate.setText("Today is : 2017 / "+ (mydate.getMonth()+1)+ " / "+mydate.getDate()+"   "+mydate.getHours()+" : "+mydate.getMinutes()+" : "+mydate.getSeconds());
            
        }
    };
    new javax.swing.Timer(1000, actiondate).start();
    }
    
    /*public void currentdate()
    {
        Calendar cal=new GregorianCalendar();
        int month=cal.get(Calendar.MONTH);
        int year=cal.get(Calendar.YEAR);
        int day=cal.get(Calendar.DAY_OF_MONTH);
        lblDate.setText(year+"/"+(month)+"/"+day);
        
    
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Home_Log_Out = new javax.swing.JButton();
        btn_Home_Supplier = new javax.swing.JButton();
        btnHome_Customer = new javax.swing.JButton();
        btnHome_Stock = new javax.swing.JButton();
        btnHome_Transactions = new javax.swing.JButton();
        btnHome_Users = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        btnHome_Settings = new javax.swing.JButton();
        btnHome_Inventory = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Home_Log_Out.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_Home_Log_Out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop/billing/sw/images/icons/1482769422_lock.png"))); // NOI18N
        btn_Home_Log_Out.setText("LOG OUT");
        btn_Home_Log_Out.setContentAreaFilled(false);
        btn_Home_Log_Out.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_Home_Log_OutMouseMoved(evt);
            }
        });
        btn_Home_Log_Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Home_Log_OutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Home_Log_Out, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, 200, 180));

        btn_Home_Supplier.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_Home_Supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop/billing/sw/images/icons/1482758643_user3.png"))); // NOI18N
        btn_Home_Supplier.setText("SUPPLIER");
        btn_Home_Supplier.setContentAreaFilled(false);
        btn_Home_Supplier.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_Home_SupplierMouseMoved(evt);
            }
        });
        btn_Home_Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Home_SupplierActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Home_Supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 230, 130));

        btnHome_Customer.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnHome_Customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop/billing/sw/images/icons/1482758626_user1.png"))); // NOI18N
        btnHome_Customer.setText("CUSTOMER");
        btnHome_Customer.setContentAreaFilled(false);
        btnHome_Customer.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnHome_CustomerMouseMoved1(evt);
            }
        });
        btnHome_Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome_CustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome_Customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, -1, 110));

        btnHome_Stock.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnHome_Stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop/billing/sw/images/icons/1482768011_blockdevice.png"))); // NOI18N
        btnHome_Stock.setText("STOCK");
        btnHome_Stock.setContentAreaFilled(false);
        btnHome_Stock.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnHome_StockMouseMoved(evt);
            }
        });
        btnHome_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome_StockActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome_Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 260, 120));

        btnHome_Transactions.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnHome_Transactions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop/billing/sw/images/icons/1482842330_checkout.png"))); // NOI18N
        btnHome_Transactions.setText("TRANSACTIONS");
        btnHome_Transactions.setContentAreaFilled(false);
        btnHome_Transactions.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnHome_TransactionsMouseMoved(evt);
            }
        });
        btnHome_Transactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome_TransactionsActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome_Transactions, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 540, -1, 100));

        btnHome_Users.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnHome_Users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop/billing/sw/images/icons/1482769613_people.png"))); // NOI18N
        btnHome_Users.setText("USERS");
        btnHome_Users.setContentAreaFilled(false);
        btnHome_Users.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnHome_UsersMouseMoved(evt);
            }
        });
        btnHome_Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome_UsersActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome_Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 170, 170));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1007, Short.MAX_VALUE)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnHome_Settings.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnHome_Settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop/billing/sw/images/1482758661_settings.png"))); // NOI18N
        btnHome_Settings.setText("SETTINGS");
        btnHome_Settings.setContentAreaFilled(false);
        btnHome_Settings.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnHome_SettingsMouseMoved(evt);
            }
        });
        btnHome_Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome_SettingsActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome_Settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 110, 170, 80));

        btnHome_Inventory.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnHome_Inventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop/billing/sw/images/icons/1482767832_checkout.png"))); // NOI18N
        btnHome_Inventory.setText("INVENTORY");
        btnHome_Inventory.setContentAreaFilled(false);
        btnHome_Inventory.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnHome_InventoryMouseMoved(evt);
            }
        });
        btnHome_Inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome_InventoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome_Inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 240, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop/billing/sw/images/final (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -240, 1870, 1320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Home_Log_OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Home_Log_OutActionPerformed
        // TODO add your handling code here:
        int p=JOptionPane.showConfirmDialog(null, "Do You Want to LogOut ?","LOGOUT",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
        Login log=new Login();
        log.setVisible(true);
        dispose();
        }else{}
    }//GEN-LAST:event_btn_Home_Log_OutActionPerformed

    private void btnHome_InventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome_InventoryActionPerformed
        // TODO add your handling code here:
        
        Inventory_JFrame inv=new Inventory_JFrame();
        inv.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnHome_InventoryActionPerformed

    private void btnHome_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome_StockActionPerformed
        // TODO add your handling code here:
        
        Stock stk=new Stock();
        stk.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHome_StockActionPerformed

    private void btnHome_UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome_UsersActionPerformed
        // TODO add your handling code here:
       
        Users user=new Users();
        user.setVisible(true);
         dispose();
    }//GEN-LAST:event_btnHome_UsersActionPerformed

    private void btnHome_SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome_SettingsActionPerformed
        // TODO add your handling code here:
        
        Settings stng=new Settings();
        stng.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnHome_SettingsActionPerformed

    private void btnHome_TransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome_TransactionsActionPerformed
        // TODO add your handling code here:
        Transactions trans=new Transactions();
        trans.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnHome_TransactionsActionPerformed

    private void btnHome_CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome_CustomerActionPerformed
        // TODO add your handling code here:
        CustomerDetails cust=new CustomerDetails();
        cust.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHome_CustomerActionPerformed

    private void btn_Home_SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Home_SupplierActionPerformed
        // TODO add your handling code here:
        SupplierDetails sup=new SupplierDetails();
        sup.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_Home_SupplierActionPerformed

    private void btnHome_CustomerMouseMoved1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome_CustomerMouseMoved1
        // TODO add your handling code here:
        btnHome_Customer.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnHome_CustomerMouseMoved1

    private void btnHome_UsersMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome_UsersMouseMoved
        // TODO add your handling code here:
        btnHome_Users.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnHome_UsersMouseMoved

    private void btn_Home_SupplierMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Home_SupplierMouseMoved
        // TODO add your handling code here:
        btn_Home_Supplier.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_Home_SupplierMouseMoved

    private void btnHome_TransactionsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome_TransactionsMouseMoved
        // TODO add your handling code here:
        btnHome_Transactions.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnHome_TransactionsMouseMoved

    private void btn_Home_Log_OutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Home_Log_OutMouseMoved
        // TODO add your handling code here:
        btn_Home_Log_Out.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_Home_Log_OutMouseMoved

    private void btnHome_StockMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome_StockMouseMoved
        // TODO add your handling code here:
        btnHome_Stock.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnHome_StockMouseMoved

    private void btnHome_InventoryMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome_InventoryMouseMoved
        // TODO add your handling code here:
        btnHome_Inventory.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnHome_InventoryMouseMoved

    private void btnHome_SettingsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome_SettingsMouseMoved
        // TODO add your handling code here:
        btnHome_Settings.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnHome_SettingsMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome_Customer;
    private javax.swing.JButton btnHome_Inventory;
    private javax.swing.JButton btnHome_Settings;
    private javax.swing.JButton btnHome_Stock;
    private javax.swing.JButton btnHome_Transactions;
    private javax.swing.JButton btnHome_Users;
    private javax.swing.JButton btn_Home_Log_Out;
    private javax.swing.JButton btn_Home_Supplier;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDate;
    // End of variables declaration//GEN-END:variables
}
