/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.billing.sw;

import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;



/**
 *
 * @author ASUS_PC
 */
public class Inventory_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form Inventory_JFrame
     */
    public Inventory_JFrame() {
        initComponents();
        Home h=new Home();
        
        h.setdate();
    }
   
    private final Cursor handCursor = new Cursor(Cursor.HAND_CURSOR);
   private final Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
  
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inventary_Header = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Inventary_Block1 = new javax.swing.JPanel();
        Inventory_Block1_Sub1 = new javax.swing.JPanel();
        Sub1_Lbl1 = new javax.swing.JLabel();
        Sub1_Lbl4 = new javax.swing.JLabel();
        Inventory_Block1_Sub2 = new javax.swing.JPanel();
        Sub2_Lbl1 = new javax.swing.JLabel();
        Sub2_Lbl2 = new javax.swing.JLabel();
        Sub2_Lbl3 = new javax.swing.JLabel();
        txtTotal_Items = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtDiscount = new javax.swing.JTextField();
        Sub3_Lbl1 = new javax.swing.JLabel();
        txtSub_Total = new javax.swing.JTextField();
        Inventory_Block1_Sub3 = new javax.swing.JPanel();
        Sub2_Lbl5 = new javax.swing.JLabel();
        Sub2_Lbl6 = new javax.swing.JLabel();
        txtCash = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        btnCancle = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        Inventory_Block1_Sub4 = new javax.swing.JPanel();
        Sub1_Lbl5 = new javax.swing.JLabel();
        Sub1_Lbl6 = new javax.swing.JLabel();
        Inventory_Block1_Sub8 = new javax.swing.JPanel();
        Sub1_Lbl13 = new javax.swing.JLabel();
        Sub1_Lbl14 = new javax.swing.JLabel();
        Inventory_Block1_Sub5 = new javax.swing.JPanel();
        Sub1_Lbl7 = new javax.swing.JLabel();
        Sub1_Lbl8 = new javax.swing.JLabel();
        Inventory_Block1_Sub9 = new javax.swing.JPanel();
        Sub1_Lbl15 = new javax.swing.JLabel();
        Sub1_Lbl3 = new javax.swing.JLabel();
        txtProduct_No = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox();
        cmbProduct_Name = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnStock = new javax.swing.JButton();
        btnCustomers = new javax.swing.JButton();
        btnTransactions = new javax.swing.JButton();
        btnLog_Out = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Inventory = new javax.swing.JTable();
        btnPrint = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventary");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        Inventary_Header.setBackground(new java.awt.Color(0, 51, 255));
        Inventary_Header.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Inventary_Header.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Shan Trade Centre");

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("For Provide Good Service Everytime..");

        javax.swing.GroupLayout Inventary_HeaderLayout = new javax.swing.GroupLayout(Inventary_Header);
        Inventary_Header.setLayout(Inventary_HeaderLayout);
        Inventary_HeaderLayout.setHorizontalGroup(
            Inventary_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Inventary_HeaderLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Inventary_HeaderLayout.setVerticalGroup(
            Inventary_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventary_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Inventary_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        Inventary_Block1.setBackground(new java.awt.Color(255, 255, 255));
        Inventary_Block1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Inventory_Block1_Sub1.setBackground(new java.awt.Color(102, 102, 102));
        Inventory_Block1_Sub1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Sub1_Lbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sub1_Lbl1.setForeground(new java.awt.Color(255, 255, 255));
        Sub1_Lbl1.setText("X");

        Sub1_Lbl4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sub1_Lbl4.setForeground(new java.awt.Color(255, 255, 255));
        Sub1_Lbl4.setText("Price");

        javax.swing.GroupLayout Inventory_Block1_Sub1Layout = new javax.swing.GroupLayout(Inventory_Block1_Sub1);
        Inventory_Block1_Sub1.setLayout(Inventory_Block1_Sub1Layout);
        Inventory_Block1_Sub1Layout.setHorizontalGroup(
            Inventory_Block1_Sub1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventory_Block1_Sub1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Sub1_Lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sub1_Lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        Inventory_Block1_Sub1Layout.setVerticalGroup(
            Inventory_Block1_Sub1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Inventory_Block1_Sub1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Inventory_Block1_Sub1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sub1_Lbl1)
                    .addComponent(Sub1_Lbl4))
                .addContainerGap())
        );

        Inventory_Block1_Sub2.setBackground(new java.awt.Color(102, 102, 102));
        Inventory_Block1_Sub2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Sub2_Lbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sub2_Lbl1.setForeground(new java.awt.Color(255, 255, 255));
        Sub2_Lbl1.setText("Total Items :");

        Sub2_Lbl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sub2_Lbl2.setForeground(new java.awt.Color(255, 255, 255));
        Sub2_Lbl2.setText("Total       :");

        Sub2_Lbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sub2_Lbl3.setForeground(new java.awt.Color(255, 255, 255));
        Sub2_Lbl3.setText("Discount      :");

        txtTotal_Items.setAutoscrolls(false);

        txtTotal.setAutoscrolls(false);

        txtDiscount.setAutoscrolls(false);

        Sub3_Lbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sub3_Lbl1.setForeground(new java.awt.Color(255, 255, 255));
        Sub3_Lbl1.setText("SubTotal :");

        txtSub_Total.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        txtSub_Total.setAutoscrolls(false);

        javax.swing.GroupLayout Inventory_Block1_Sub2Layout = new javax.swing.GroupLayout(Inventory_Block1_Sub2);
        Inventory_Block1_Sub2.setLayout(Inventory_Block1_Sub2Layout);
        Inventory_Block1_Sub2Layout.setHorizontalGroup(
            Inventory_Block1_Sub2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventory_Block1_Sub2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Inventory_Block1_Sub2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sub2_Lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sub2_Lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Inventory_Block1_Sub2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotal_Items)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(Inventory_Block1_Sub2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Inventory_Block1_Sub2Layout.createSequentialGroup()
                        .addComponent(Sub2_Lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Inventory_Block1_Sub2Layout.createSequentialGroup()
                        .addComponent(Sub3_Lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSub_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Inventory_Block1_Sub2Layout.setVerticalGroup(
            Inventory_Block1_Sub2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventory_Block1_Sub2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Inventory_Block1_Sub2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sub2_Lbl1)
                    .addComponent(Sub2_Lbl2)
                    .addComponent(txtTotal_Items, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(Inventory_Block1_Sub2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sub2_Lbl3)
                    .addComponent(Sub3_Lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSub_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Inventory_Block1_Sub3.setBackground(new java.awt.Color(102, 102, 102));
        Inventory_Block1_Sub3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Sub2_Lbl5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sub2_Lbl5.setForeground(new java.awt.Color(255, 255, 255));
        Sub2_Lbl5.setText("Cash            :");

        Sub2_Lbl6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sub2_Lbl6.setForeground(new java.awt.Color(255, 255, 255));
        Sub2_Lbl6.setText("Balance    :");

        txtCash.setAutoscrolls(false);

        txtBalance.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        txtBalance.setAutoscrolls(false);

        javax.swing.GroupLayout Inventory_Block1_Sub3Layout = new javax.swing.GroupLayout(Inventory_Block1_Sub3);
        Inventory_Block1_Sub3.setLayout(Inventory_Block1_Sub3Layout);
        Inventory_Block1_Sub3Layout.setHorizontalGroup(
            Inventory_Block1_Sub3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventory_Block1_Sub3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Sub2_Lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCash, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(Sub2_Lbl6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Inventory_Block1_Sub3Layout.setVerticalGroup(
            Inventory_Block1_Sub3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Inventory_Block1_Sub3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(Inventory_Block1_Sub3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sub2_Lbl5)
                    .addComponent(Sub2_Lbl6)
                    .addComponent(txtCash, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnCancle.setBackground(new java.awt.Color(102, 0, 102));
        btnCancle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancle.setForeground(new java.awt.Color(255, 255, 255));
        btnCancle.setText("CANCLE");
        btnCancle.setBorder(null);

        btnRefresh.setBackground(new java.awt.Color(102, 0, 102));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("REFRESH");
        btnRefresh.setBorder(null);

        btnPayment.setBackground(new java.awt.Color(102, 0, 102));
        btnPayment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnPayment.setText("PAYMENT");
        btnPayment.setBorder(null);

        Inventory_Block1_Sub4.setBackground(new java.awt.Color(102, 102, 102));
        Inventory_Block1_Sub4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Sub1_Lbl5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sub1_Lbl5.setForeground(new java.awt.Color(255, 255, 255));
        Sub1_Lbl5.setText("X");

        Sub1_Lbl6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sub1_Lbl6.setForeground(new java.awt.Color(255, 255, 255));
        Sub1_Lbl6.setText("Product Category");

        javax.swing.GroupLayout Inventory_Block1_Sub4Layout = new javax.swing.GroupLayout(Inventory_Block1_Sub4);
        Inventory_Block1_Sub4.setLayout(Inventory_Block1_Sub4Layout);
        Inventory_Block1_Sub4Layout.setHorizontalGroup(
            Inventory_Block1_Sub4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventory_Block1_Sub4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Sub1_Lbl5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sub1_Lbl6)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        Inventory_Block1_Sub4Layout.setVerticalGroup(
            Inventory_Block1_Sub4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Inventory_Block1_Sub4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Inventory_Block1_Sub4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sub1_Lbl5)
                    .addComponent(Sub1_Lbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Inventory_Block1_Sub8.setBackground(new java.awt.Color(102, 102, 102));
        Inventory_Block1_Sub8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Sub1_Lbl13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sub1_Lbl13.setForeground(new java.awt.Color(255, 255, 255));
        Sub1_Lbl13.setText("X");

        Sub1_Lbl14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sub1_Lbl14.setForeground(new java.awt.Color(255, 255, 255));
        Sub1_Lbl14.setText("Product Name");

        javax.swing.GroupLayout Inventory_Block1_Sub8Layout = new javax.swing.GroupLayout(Inventory_Block1_Sub8);
        Inventory_Block1_Sub8.setLayout(Inventory_Block1_Sub8Layout);
        Inventory_Block1_Sub8Layout.setHorizontalGroup(
            Inventory_Block1_Sub8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventory_Block1_Sub8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Sub1_Lbl13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sub1_Lbl14)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        Inventory_Block1_Sub8Layout.setVerticalGroup(
            Inventory_Block1_Sub8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Inventory_Block1_Sub8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Inventory_Block1_Sub8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sub1_Lbl13)
                    .addComponent(Sub1_Lbl14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Inventory_Block1_Sub5.setBackground(new java.awt.Color(102, 102, 102));
        Inventory_Block1_Sub5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Sub1_Lbl7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sub1_Lbl7.setForeground(new java.awt.Color(255, 255, 255));
        Sub1_Lbl7.setText("X");

        Sub1_Lbl8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sub1_Lbl8.setForeground(new java.awt.Color(255, 255, 255));
        Sub1_Lbl8.setText("Product");

        javax.swing.GroupLayout Inventory_Block1_Sub5Layout = new javax.swing.GroupLayout(Inventory_Block1_Sub5);
        Inventory_Block1_Sub5.setLayout(Inventory_Block1_Sub5Layout);
        Inventory_Block1_Sub5Layout.setHorizontalGroup(
            Inventory_Block1_Sub5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventory_Block1_Sub5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Sub1_Lbl7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sub1_Lbl8)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        Inventory_Block1_Sub5Layout.setVerticalGroup(
            Inventory_Block1_Sub5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Inventory_Block1_Sub5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Inventory_Block1_Sub5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sub1_Lbl7)
                    .addComponent(Sub1_Lbl8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Inventory_Block1_Sub9.setBackground(new java.awt.Color(102, 102, 102));
        Inventory_Block1_Sub9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Sub1_Lbl15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sub1_Lbl15.setForeground(new java.awt.Color(255, 255, 255));
        Sub1_Lbl15.setText("X");

        Sub1_Lbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sub1_Lbl3.setForeground(new java.awt.Color(255, 255, 255));
        Sub1_Lbl3.setText("Qty.");

        javax.swing.GroupLayout Inventory_Block1_Sub9Layout = new javax.swing.GroupLayout(Inventory_Block1_Sub9);
        Inventory_Block1_Sub9.setLayout(Inventory_Block1_Sub9Layout);
        Inventory_Block1_Sub9Layout.setHorizontalGroup(
            Inventory_Block1_Sub9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventory_Block1_Sub9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Sub1_Lbl15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sub1_Lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Inventory_Block1_Sub9Layout.setVerticalGroup(
            Inventory_Block1_Sub9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Inventory_Block1_Sub9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Inventory_Block1_Sub9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sub1_Lbl15)
                    .addComponent(Sub1_Lbl3))
                .addContainerGap())
        );

        txtProduct_No.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        txtProduct_No.setAutoscrolls(false);

        txtQty.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        txtQty.setAutoscrolls(false);
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });

        txtPrice.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        txtPrice.setAutoscrolls(false);

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbProduct_Name.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel2.setBackground(new java.awt.Color(56, 52, 52));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(56, 52, 52));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Inventary_Block1Layout = new javax.swing.GroupLayout(Inventary_Block1);
        Inventary_Block1.setLayout(Inventary_Block1Layout);
        Inventary_Block1Layout.setHorizontalGroup(
            Inventary_Block1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Inventary_Block1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(Inventary_Block1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Inventory_Block1_Sub2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Inventory_Block1_Sub3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Inventary_Block1Layout.createSequentialGroup()
                        .addComponent(btnCancle, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Inventary_Block1Layout.createSequentialGroup()
                        .addComponent(Inventory_Block1_Sub5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProduct_No))
                    .addGroup(Inventary_Block1Layout.createSequentialGroup()
                        .addGroup(Inventary_Block1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Inventory_Block1_Sub1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Inventory_Block1_Sub9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Inventary_Block1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQty)
                            .addComponent(txtPrice)))
                    .addGroup(Inventary_Block1Layout.createSequentialGroup()
                        .addGroup(Inventary_Block1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Inventory_Block1_Sub8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Inventory_Block1_Sub4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Inventary_Block1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbProduct_Name, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Inventary_Block1Layout.setVerticalGroup(
            Inventary_Block1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventary_Block1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(Inventary_Block1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Inventory_Block1_Sub4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbCategory))
                .addGap(18, 18, 18)
                .addGroup(Inventary_Block1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Inventory_Block1_Sub8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbProduct_Name))
                .addGap(18, 18, 18)
                .addGroup(Inventary_Block1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtProduct_No)
                    .addComponent(Inventory_Block1_Sub5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Inventary_Block1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtQty)
                    .addComponent(Inventory_Block1_Sub9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Inventary_Block1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Inventory_Block1_Sub1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrice))
                .addGap(18, 18, 18)
                .addComponent(Inventory_Block1_Sub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inventory_Block1_Sub3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Inventary_Block1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(56, 52, 52));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(56, 52, 52));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        btnHome.setBackground(new java.awt.Color(153, 0, 0));
        btnHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(153, 0, 0));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop/billing/sw/images/icons/1482937563_Pharmacy.png"))); // NOI18N
        btnHome.setText("HOME");
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnHome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnHomeMouseMoved(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnStock.setBackground(new java.awt.Color(153, 0, 0));
        btnStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnStock.setForeground(new java.awt.Color(153, 0, 0));
        btnStock.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS_PC\\Downloads\\1482938056_stock-market.png")); // NOI18N
        btnStock.setText(" STOCK");
        btnStock.setBorder(null);
        btnStock.setBorderPainted(false);
        btnStock.setContentAreaFilled(false);
        btnStock.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnStock.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnStockMouseMoved(evt);
            }
        });
        btnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockActionPerformed(evt);
            }
        });

        btnCustomers.setBackground(new java.awt.Color(153, 0, 0));
        btnCustomers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCustomers.setForeground(new java.awt.Color(153, 0, 0));
        btnCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop/billing/sw/images/1482758626_user1.png"))); // NOI18N
        btnCustomers.setText("CUSTOMERS");
        btnCustomers.setBorder(null);
        btnCustomers.setBorderPainted(false);
        btnCustomers.setContentAreaFilled(false);
        btnCustomers.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnCustomers.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnCustomersMouseMoved(evt);
            }
        });
        btnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersActionPerformed(evt);
            }
        });

        btnTransactions.setBackground(new java.awt.Color(153, 0, 0));
        btnTransactions.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTransactions.setForeground(new java.awt.Color(153, 0, 0));
        btnTransactions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop/billing/sw/images/1482937876_23.png"))); // NOI18N
        btnTransactions.setText("TRANSACTIONS");
        btnTransactions.setBorder(null);
        btnTransactions.setBorderPainted(false);
        btnTransactions.setContentAreaFilled(false);
        btnTransactions.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnTransactions.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnTransactionsMouseMoved(evt);
            }
        });
        btnTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactionsActionPerformed(evt);
            }
        });

        btnLog_Out.setBackground(new java.awt.Color(153, 0, 0));
        btnLog_Out.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLog_Out.setForeground(new java.awt.Color(153, 0, 0));
        btnLog_Out.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS_PC\\Downloads\\1482758669_key.png")); // NOI18N
        btnLog_Out.setText(" LOGOUT");
        btnLog_Out.setBorder(null);
        btnLog_Out.setBorderPainted(false);
        btnLog_Out.setContentAreaFilled(false);
        btnLog_Out.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btnLog_Out.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnLog_OutMouseMoved(evt);
            }
        });
        btnLog_Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLog_OutActionPerformed(evt);
            }
        });

        jLabel1.setText("SHAN TRADE CENTRE\n");

        jLabel2.setText("NCP/KD/249\n");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTransactions, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLog_Out)
                    .addComponent(btnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLog_Out, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbl_Inventory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_Inventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Product", "Qty.", "Total"
            }
        ));
        jScrollPane1.setViewportView(tbl_Inventory);

        btnPrint.setBackground(new java.awt.Color(0, 51, 255));
        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("PRINT BILL");
        btnPrint.setBorder(null);
        btnPrint.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnPrintMouseMoved(evt);
            }
        });
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 51, 51));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("EXIT");
        btnExit.setBorder(null);
        btnExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnExitMouseMoved(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Inventary_Block1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
            .addComponent(Inventary_Header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Inventary_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Inventary_Block1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        btnExit.setCursor(new Cursor(Cursor.HAND_CURSOR));
        int p=JOptionPane.showConfirmDialog(null, "Do You Want Exit to Home ?","EXIT",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
        dispose();
        Home home=new Home();
        home.setVisible(true);
        }else{}
        
        
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockActionPerformed
        // TODO add your handling code here:
        
        btnStock.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Stock stk=new Stock();
        stk.setVisible(true);
        dispose();
         
    }//GEN-LAST:event_btnStockActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        btnHome.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Home home=new Home();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnLog_OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLog_OutActionPerformed
        // TODO add your handling code here:
        btnLog_Out.setCursor(new Cursor(Cursor.HAND_CURSOR));
        int p=JOptionPane.showConfirmDialog(null, "Do You Want to LogOut ?","LOGOUT",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
        Login log=new Login();
        log.setVisible(true);
        dispose();
        }else{}
    }//GEN-LAST:event_btnLog_OutActionPerformed

    private void btnTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionsActionPerformed
        // TODO add your handling code here:
        btnTransactions.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Transactions trans=new Transactions();
        trans.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTransactionsActionPerformed

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        // TODO add your handling code here:
        btnCustomers.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Home home=new Home();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCustomersActionPerformed

    private void btnHomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseMoved
        // TODO add your handling code here:
        btnHome.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnHomeMouseMoved

    private void btnStockMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStockMouseMoved
        // TODO add your handling code here:
        btnStock.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnStockMouseMoved

    private void btnCustomersMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomersMouseMoved
        // TODO add your handling code here:
        btnCustomers.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnCustomersMouseMoved

    private void btnTransactionsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransactionsMouseMoved
        // TODO add your handling code here:
        btnTransactions.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnTransactionsMouseMoved

    private void btnLog_OutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLog_OutMouseMoved
        // TODO add your handling code here:
        btnLog_Out.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnLog_OutMouseMoved

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnPrintMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseMoved
        // TODO add your handling code here:
        btnPrint.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnPrintMouseMoved

    private void btnExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseMoved
        // TODO add your handling code here:
        btnExit.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnExitMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Inventary_Block1;
    private javax.swing.JPanel Inventary_Header;
    private javax.swing.JPanel Inventory_Block1_Sub1;
    private javax.swing.JPanel Inventory_Block1_Sub2;
    private javax.swing.JPanel Inventory_Block1_Sub3;
    private javax.swing.JPanel Inventory_Block1_Sub4;
    private javax.swing.JPanel Inventory_Block1_Sub5;
    private javax.swing.JPanel Inventory_Block1_Sub8;
    private javax.swing.JPanel Inventory_Block1_Sub9;
    private javax.swing.JLabel Sub1_Lbl1;
    private javax.swing.JLabel Sub1_Lbl13;
    private javax.swing.JLabel Sub1_Lbl14;
    private javax.swing.JLabel Sub1_Lbl15;
    private javax.swing.JLabel Sub1_Lbl3;
    private javax.swing.JLabel Sub1_Lbl4;
    private javax.swing.JLabel Sub1_Lbl5;
    private javax.swing.JLabel Sub1_Lbl6;
    private javax.swing.JLabel Sub1_Lbl7;
    private javax.swing.JLabel Sub1_Lbl8;
    private javax.swing.JLabel Sub2_Lbl1;
    private javax.swing.JLabel Sub2_Lbl2;
    private javax.swing.JLabel Sub2_Lbl3;
    private javax.swing.JLabel Sub2_Lbl5;
    private javax.swing.JLabel Sub2_Lbl6;
    private javax.swing.JLabel Sub3_Lbl1;
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLog_Out;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnStock;
    private javax.swing.JButton btnTransactions;
    private javax.swing.JComboBox cmbCategory;
    private javax.swing.JComboBox cmbProduct_Name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Inventory;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProduct_No;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSub_Total;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotal_Items;
    // End of variables declaration//GEN-END:variables
}
